fix(workflow): update input variable names and improve output handling
Renames input variable from 'json-in' to 'var-name' for clarity.
Enhances output handling by consolidating output values from
multiple steps, ensuring more reliable data retrieval and
processing in the action workflow.

Signed-off-by: DCx7C5 <dcxdevelopment@protonmail.com>

diff --git a/aur-json-packages/action.yml b/aur-json-packages/action.yml
--- a/aur-json-packages/action.yml
+++ b/aur-json-packages/action.yml
@@ -8,7 +8,7 @@ branding:
 
 
 inputs:
-  json-in:
+  var-name:
     required: false
     description: "Name of variable that stores JSON package dictionary (default: JSON_PACKAGES)."
     default: 'JSON_PACKAGES'
@@ -59,53 +59,39 @@ inputs:
 outputs:
   out:
     description: "Output channel for the action. "
-    value: ${{ steps.convert_output.outputs.out || steps.run_action.outputs.out }}
+    value: ${{ steps.convert_output.outputs.out || steps.build_get_args.outputs.out || steps.build_add_args.outputs.out || steps.build_del_args.outputs.out }}
   debug-args:
     description: "Debug output containing the generated jq filter and arguments for troubleshooting (only if 'step_summary' input is set to 'true')."
-    value: ${{ steps.run_action.outputs.args }}
+    value: ${{ steps.build_get_args.outputs.args || steps.build_add_args.outputs.args || steps.build_del_args.outputs.args }}
   debug-filter:
     description: "Debug output containing the generated jq filter for troubleshooting (only if 'step_summary' input is set to 'true')."
-    value: ${{ steps.run_action.outputs.filter }}
+    value: ${{ steps.build_get_args.outputs.filter || steps.build_add_args.outputs.filter || steps.build_del_args.outputs.filter }}
 
 
 runs:
   using: composite
+
   steps:
     - id: validate_inputs
       shell: bash
       env:
-        JSON_PATH: "${{ inputs.json-in }}"
+        JSON_VAR_NAME: "${{ inputs.var-name }}"
         GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
         ACTION: "${{ inputs.action }}"
+        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
+        INPUT_KEYS: "${{ inputs.key }}"
+        INPUT_VALUES: "${{ inputs.value }}"
       run: |
-        valid_actions=("get" "add" "update" "remove" "count" "delete")
-                
-        if [[ ! " ${valid_actions[*]} " =~ " ${ACTION} " ]]; then
+        
+        if [[ ! "$ACTION" =~ ^(get|add|update|remove|count|delete)$ ]]; then
           echo "::error::Invalid action '${ACTION}'. Valid actions are: ${valid_actions[*]}" >&2
           exit 1
         fi
-
-        if [[ -n "$JSON_PATH" && -f "$JSON_PATH" && $(cat "$JSON_PATH") == *$'\n'* ]]; then
-          { 
-            echo "is_file=true"
-            echo "json_input<<EOF"
-            cat "$JSON_PATH"
-            echo "EOF"
-          } >> "$GITHUB_OUTPUT"
-        elif [[ -n "$JSON_PATH" && -f "$JSON_PATH" && $(cat "$JSON_PATH") != *$'\n'* ]]; then
-          echo "json_input=$(cat "$JSON_PATH")" >> "$GITHUB_OUTPUT"
-          echo "is_file=true" >> "$GITHUB_OUTPUT"
-        elif [ -n "$JSON_PATH" ]; then
-          echo "json_input=$JSON_PATH" >> "$GITHUB_OUTPUT"
-        else
-          echo "::error::'json_file' input is required and must point to a valid file or variable name." >&2
-          exit 1
-        fi
-
+        
         count=0
-        [ -n "${{ inputs.env }}" ] && ((count+=1))
-        [ -n "${{ inputs.repo }}" ] && ((count+=1))
-        [ -n "${{ inputs.org }}" ] && ((count+=1))
+        [ -n  ] && ((count+=1))
+        [ -n  ] && ((count+=1))
+        [ -n  ] && ((count+=1))
         
         if (( count > 1 )); then
           echo "::error::Not more than one of 'env', 'repo' or 'org' can be set to a non-empty value" >&2
@@ -119,7 +105,6 @@ runs:
         
         if echo '${{ inputs.value }}' | jq -e 2>/dev/null; then
           echo "json_value=true" >> "$GITHUB_OUTPUT"
-          
         else
           echo "json_value=false" >> "$GITHUB_OUTPUT"
         fi
@@ -134,62 +119,254 @@ runs:
           echo "access_level=--repo" >> "$GITHUB_OUTPUT"
           echo "level_name=${{ inputs.repo }}" >> "$GITHUB_OUTPUT"
         fi
+        
+        if [[ -n "$INPUT_PKGNAMES" ]]; then
+          echo "lenpkg=$(printf '%s\n' "$INPUT_PKGNAMES" | wc -l)" >> "$GITHUB_OUTPUT"
+        fi
+        
+        if [[ -n "$INPUT_KEYS" ]]; then
+          echo "lenkey=$(printf '%s\n' "$INPUT_KEYS" | wc -l)" >> "$GITHUB_OUTPUT"
+        fi
+        
+        if [[ -n "$INPUT_VALUES" ]]; then
+          echo "lenval=$(printf '%s\n' "$INPUT_VALUES" | wc -l)" >> "$GITHUB_OUTPUT"
+        fi
+        
+        echo "json_dict=$(gh variable get "$JSON_VAR_NAME" ${ACCESS_LEVEL} "$LEVEL_NAME" --json value --jq '.value')" >> "$GITHUB_OUTPUT"
 
-    - name: Run Action
-      id: run_action
-      shell: bash
-      env:
-        INPUT_ACTION: "${{ inputs.action }}"
-        INPUT_JSON: "${{ steps.validate_inputs.outputs.json_input }}"
-        IS_JSON_VALUE: "${{ steps.validate_inputs.outputs.json_value }}"
-        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
-        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
-        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
-      working-directory: "${{ github.action_path }}"
-      run: |
-        INPUT_JSON=$(gh variable get "$INPUT_JSON" ${ACCESS_LEVEL} "$LEVEL_NAME" --json value --jq '.value')
-
-        if [[ -z "$INPUT_JSON"  || ! $(echo "$INPUT_JSON" | jq -c '.' 2>/dev/null) ]]; then
+        if ! echo "$JSON_VAR_NAME" | jq -c '.' 2>/dev/null; then
           echo "::error::inputs.json-in does not contain valid JSON data or is empty." >&2
           exit 1
         fi
-        
-        if [[ "$INPUT_ACTION" =~ ^(add|update)$ && -n '${{ inputs.value }}' && "$IS_JSON_VALUE" == "true" ]]; then
-          INPUT_VALUE="$(echo '${{ inputs.value }}' | tr -d ' ' | jq -c '@json')"
-          echo "DEBUG: IS JSON"
-        elif [[ "$INPUT_ACTION" =~ ^(add|update)$ && -n '${{ inputs.value }}' && "$IS_JSON_VALUE" == "false" ]]; then
-          INPUT_VALUE="${{ inputs.value }}"
-        fi
-        
-        chmod +x libpackages.sh
-        readarray -t ALL_ARGS < <(
-          ./libpackages.sh "$INPUT_ACTION" "${{ inputs.pkg-name }}" "${{ inputs.key }}" "$INPUT_VALUE" "$IS_JSON_VALUE"
-        )
-        
-        FILTER="${ALL_ARGS[-1]}"
-        unset 'ALL_ARGS[-1]'
-        ARGS=("${ALL_ARGS[@]}")
 
-        if [ "$INPUT_ACTION" = "get" ]; then
-          echo "out=$(jq -c "${ARGS[@]}" "$FILTER" <<< "$INPUT_JSON")" >> "$GITHUB_OUTPUT"
-        elif [[ "$INPUT_ACTION" =~ ^(update|add|remove|delete)$ && "$IS_FILE" == "false" ]]; then
-          if jq -c "${ARGS[@]}" "$FILTER" <<< "$INPUT_JSON" | gh variable set "${{ inputs.json-in }}" ${ACCESS_LEVEL} "$LEVEL_NAME"; then
-            echo "out=saved" >> "$GITHUB_OUTPUT"
-          fi
-        elif [ "$INPUT_ACTION" = "count" ]; then
-          echo "out=$(jq -c '.packages | length' <<< "$INPUT_JSON")" >> "$GITHUB_OUTPUT"
+    - name: Build Get Args
+      id: build_get_args
+      if: inputs.action == 'get'
+      shell: bash
+      env:
+        JSON_DICT: "${{ steps.validate_inputs.outputs.json_dict }}"
+        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
+        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
+        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
+        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
+        INPUT_KEYS: "${{ inputs.key }}"
+        LEN_PKGS: "${{ steps.validate_inputs.outputs.lenpkg }}"
+        LEN_KEYS: "${{ steps.validate_inputs.outputs.lenkey }}"
+        FILTER: '.packages'
+      run: |
+        args=()
+        INPUT_PKGNAMES_ARR=()
+        INPUT_KEYS_ARR=()
+        
+        INPUT_PKGNAMES="$(printf '%s\n' "$INPUT_PKGNAMES" | tr -d ' ')"
+        INPUT_KEYS="$(printf '%s\n' "$INPUT_KEYS" | tr -d ' ')"
+        
+        for pkg in $INPUT_PKGNAMES; do INPUT_PKGNAMES_ARR+=("$pkg"); done
+        for key in $INPUT_KEYS; do INPUT_KEYS_ARR+=("$key"); done
+        
+        # get_all_packages
+        if [[ -z "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" ]]; then
+          filter="$FILTER"
+        
+        # get_all_packages_with_keys
+        elif [[ -z "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" ]]; then
+          filter="$FILTER | map_values({"
+          for ((n=0; n<$LEN_KEYS; n++)); do
+            [[ -z "${INPUT_KEYS_ARR[n]}" ]] && continue
+            key="${INPUT_KEYS_ARR[n]}"
+            args+=(--arg "key$n" "$key")
+            filter+="\$key$n: .[\$key$n],"
+          done
+          filter="${filter%,}})"
+        
+        # get_packages_with_pkgnames
+        elif [[ -n "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" ]]; then
+          filter="$FILTER | {"
+          for ((i=0; i<$LEN_PKGS; i++)); do
+            [[ -z "${INPUT_PKGNAMES_ARR[i]}" ]] && continue
+            pkgname="${INPUT_PKGNAMES_ARR[i]}"
+            args+=(--arg "pkg$i" "$pkgname")
+            filter+="\$pkg$i: .[\$pkg$i],"
+          done
+          filter="${filter%,}}"
+        
+        # get_packages_with_pkgname_and_keys
+        elif [[ -n "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" ]]; then
+          filter="$FILTER | {"
+          for ((i=0; i<$LEN_PKGS; i++)); do
+            [[ -z "${INPUT_PKGNAMES_ARR[i]}" ]] && continue
+            pkgname="${INPUT_PKGNAMES_ARR[i]}"
+            args+=(--arg "pkg$i" "$pkgname")
+            filter+="\$pkg$i: {"
+            for ((n=0; n<$LEN_KEYS; n++)); do
+              [[ -z "${INPUT_KEYS_ARR[n]}" ]] && continue
+              key="${INPUT_KEYS_ARR[n]}"
+              args+=(--arg "key$n" "$key")
+              filter+="\$key$n: .[\$pkg$i][\$key$n],"
+            done
+            filter="${filter%,}},"
+          done
+          filter="${filter%,}}"
+        
+        else
+          echo "Invalid input combination for 'get' action." >&2
+          exit 1
         fi
         
-        echo "args=${ARGS[*]}" >> "$GITHUB_OUTPUT"
-        echo "filter='$(echo $FILTER | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"
+        echo "out=$(jq -c "${args[@]}" "$filter" <<< "$JSON_DICT")" >> "$GITHUB_OUTPUT"
+        echo "args=${args[*]}" >> "$GITHUB_OUTPUT"
+        echo "filter='$(echo $filter | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"
+        
+    
+    - name: Build Add/Update Args
+      id: build_add_args
+      if: inputs.action == 'add' || inputs.action == 'update'
+      shell: bash
+      env:
+        JSON_DICT: "${{ steps.validate_inputs.outputs.json_dict }}"
+        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
+        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
+        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
+        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
+        INPUT_KEYS: "${{ inputs.key }}"
+        INPUT_VALUES: '${{ inputs.value }}'
+        LEN_PKGS: "${{ steps.validate_inputs.outputs.lenpkg }}"
+        LEN_KEYS: "${{ steps.validate_inputs.outputs.lenkey }}"
+        LEN_VALS: "${{ steps.validate_inputs.outputs.lenval }}"
+        FILTER: '.packages'
+      run: |
+        args=()
+        INPUT_PKGNAMES_ARR=()
+        INPUT_KEYS_ARR=()
+        INPUT_VALUES_ARR=()
+        
+        INPUT_PKGNAMES="$(printf '%s\n' "$INPUT_PKGNAMES" | tr -d ' ')"
+        INPUT_KEYS="$(printf '%s\n' "$INPUT_KEYS" | tr -d ' ')"
+        INPUT_VALUES="$(printf '%s\n' "$INPUT_VALUES" | tr -d ' ')"
+        
+        for pkg in $INPUT_PKGNAMES; do INPUT_PKGNAMES_ARR+=("$pkg"); done
+        for key in $INPUT_KEYS; do INPUT_KEYS_ARR+=("$key"); done
+        for val in $INPUT_VALUES; do INPUT_VALUES_ARR+=("$val"); done
+
+        # add_package_with_one_pkgname_and_multiple_keys_and_multiple_values
+        if [[ -n "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" && -n "$INPUT_VALUES" ]]; then
+          filter="$FILTER + {\$pkg: {"
+          pkgname="${INPUT_PKGNAMES_ARR[0]}"
+          args+=(--arg "pkg" "$pkgname")
+          for ((i=0; i<$LEN_KEYS; i++)); do
+            [[ -z "${INPUT_KEYS_ARR[i]}" || -z "${INPUT_VALUES_ARR[i]}" ]] && continue
+            key="${INPUT_KEYS_ARR[i]}"
+            value="${INPUT_VALUES_ARR[i]}"
+            args+=(--arg "key$i" "$key")
+            args+=(--arg "val$i" "$value")
+            filter+="\$key$i: \$val$i,"
+          done
+          filter="${filter%,}}}"
+        
+        # add_package_with_no_pkgname_and_multiple_values_and_no_keys
+        elif [[ -z "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" && -n "$INPUT_VALUES" ]]; then
+          filter="$FILTER + "
+          for ((i=0; i<$LEN_VALS; i++)); do
+            [[ -z "${INPUT_VALUES_ARR[i]}" ]] && continue
+            value="${INPUT_VALUES_ARR[i]}"
+            args+=(--argjson "val$i" "$value")
+            filter+="\$val$i,"
+          done
+          filter="${filter%,}"
+        
+        # add_package_with_multiple_pkgnames_and_multiple_values_and_no_keys
+        elif [[ -n "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" && -n "$INPUT_VALUES" ]]; then
+          filter="$FILTER + {"
+          for ((i=0; i<$LEN_PKGS; i++)); do
+            [[ -z "${INPUT_PKGNAMES_ARR[i]}" || -z "${INPUT_VALUES_ARR[i]}" ]] && continue
+            value=${INPUT_VALUES_ARR[i]}
+            args+=(--arg "pkg$i" "${INPUT_PKGNAMES_ARR[i]}")
+            args+=(--argjson "val$i" "$value")
+            filter+="\$pkg$i: \$val$i,"
+          done
+          filter="${filter%,}}"
+        
+        else
+          echo "Invalid input combination for 'update' action." >&2
+          exit 1
+        fi
+        
+        if jq -c "${args[@]}" "$filter" <<< "$JSON_DICT" | gh variable set "${{ inputs.json-in }}" ${ACCESS_LEVEL} "$LEVEL_NAME"; then
+          echo "out=saved" >> "$GITHUB_OUTPUT"
+        fi
+        
+        echo "args=${args[*]}" >> "$GITHUB_OUTPUT"
+        echo "filter='$(echo $filter | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"
+
+
+    - name: Build Delete Args
+      id: build_del_args
+      if: inputs.action == 'delete' || inputs.action == 'remove'
+      shell: bash
+      env:
+        JSON_DICT: "${{ steps.validate_inputs.outputs.json_dict }}"
+        GH_TOKEN: "${{ inputs.gh-token || env.GH_TOKEN || env.GITHUB_TOKEN }}"
+        ACCESS_LEVEL: "${{ steps.validate_inputs.outputs.access_level }}"
+        LEVEL_NAME: "${{ steps.validate_inputs.outputs.level_name }}"
+        INPUT_PKGNAMES: "${{ inputs.pkg-name }}"
+        INPUT_KEYS: "${{ inputs.key }}"
+        LEN_PKGS: "${{ steps.validate_inputs.outputs.lenpkg }}"
+        LEN_KEYS: "${{ steps.validate_inputs.outputs.lenkey }}"
+        FILTER: '.packages'
+      run: |
+        args=()
+        
+        INPUT_PKGNAMES_ARR=()
+        INPUT_KEYS_ARR=()
+        
+        INPUT_PKGNAMES="$(printf '%s\n' "$INPUT_PKGNAMES" | tr -d ' ')"
+        INPUT_KEYS="$(printf '%s\n' "$INPUT_KEYS" | tr -d ' ')"
+        
+        for pkg in $INPUT_PKGNAMES; do INPUT_PKGNAMES_ARR+=("$pkg"); done
+        for key in $INPUT_KEYS; do INPUT_KEYS_ARR+=("$key"); done
+        
+        # remove_packages_with_multiple_pkgnames
+        if [[ -n "$INPUT_PKGNAMES" && -z "$INPUT_KEYS" ]]; then
+          filter="$FILTER | del("
+          for ((i=0; i<$LEN_PKGS; i++)); do
+            [[ -z "${INPUT_PKGNAMES_ARR[i]}" ]] && continue
+            args+=(--arg "pkg$i" "${INPUT_PKGNAMES_ARR[i]}")
+            filter+=".[\$pkg$i],"
+          done
+          filter="${filter%,})"
+        
+        # remove_from_one_package_multiple_keys
+        elif [[ -n "$INPUT_PKGNAMES" && -n "$INPUT_KEYS" ]]; then
+          filter="$FILTER |= (.[\$pkg] |= del("
+          pkgname="${INPUT_PKGNAMES_ARR[0]}"
+          args+=(--arg "pkg" "$pkgname")
+          for ((i=0; i<$LEN_KEYS; i++)); do
+            [[ -z "${INPUT_KEYS_ARR[i]}" ]] && continue
+            key="${INPUT_KEYS_ARR[i]}"
+            args+=(--arg "key$i" "$key")
+            filter+=".[\$key$i],"
+          done
+          filter="${filter%,}))"
+        
+        else
+          echo "Invalid input combination for 'remove' action." >&2
+          exit 1
+        fi
+
+        if jq -c "${args[@]}" "$filter" <<< "$JSON_DICT" | gh variable set "${{ inputs.json-in }}" ${ACCESS_LEVEL} "$LEVEL_NAME"; then
+          echo "out=saved" >> "$GITHUB_OUTPUT"
+        fi
+        
+        echo "args=${args[*]}" >> "$GITHUB_OUTPUT"
+        echo "filter='$(echo $filter | sed -e 's/\$/\\$/g')'" >> "$GITHUB_OUTPUT"
 
     - name: Convert output format
       id: convert_output
       if: inputs.output-structure == 'list' && inputs.action == 'get'
       shell: bash
       run: |
-        if [ -n "${{ steps.run_action.outputs.out }}" ]; then
-          echo "out=$(echo '${{ steps.run_action.outputs.out }}' | jq -c 'to_entries | map({name: .key} + .value)')" >> "$GITHUB_OUTPUT"
+        if [ -n "${{ steps.build_get_args.outputs.out }}" ]; then
+          echo "out=$(echo '${{ steps.build_get_args.outputs.out }}' | jq -c 'to_entries | map({name: .key} + .value)')" >> "$GITHUB_OUTPUT"
         else
           echo "out=[]" >> "$GITHUB_OUTPUT"
         fi
